# Generated by Django 2.2.1 on 2019-05-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetail',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
